name: 自动构建/发布
on:
  workflow_dispatch:
    
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-x86_64-unknown-linux-musl:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          
      - name: Install cross-rs
        run: |
          cargo install cross
          
      - name: Build x86_64-unknown-linux-musl
        run: |
          cross build --release --target x86_64-unknown-linux-musl

      - name: Save the file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: NjtechQuickLogin-x86_64-unknown-linux-musl
          path: target/x86_64-unknown-linux-musl/release/NjtechQuickLogin
  build-x86_64-unknown-linux-gnu:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          
      - name: Install cross-rs
        run: |
          cargo install cross

      - name: Build x86_64-unknown-linux-gnu
        run: |
          cross build --release --target x86_64-unknown-linux-gnu

      - name: Save the file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: NjtechQuickLogin-x86_64-unknown-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/NjtechQuickLogin
    
  build-aarch64-unknown-linux-gnu:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          
      - name: Install cross-rs
        run: |
          cargo install cross

      - name: Build aarch64-unknown-linux-gnu
        run: |
          cross build --release --target aarch64-unknown-linux-gnu
      
      - name: Save the file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: NjtechQuickLogin-aarch64-unknown-linux-gnu
          path: target/aarch64-unknown-linux-gnu/release/NjtechQuickLogin
  build-aarch64-unknown-linux-musl:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          
      - name: Install cross-rs
        run: |
          cargo install cross

      - name: Build aarch64-unknown-linux-musl
        run: |
          cross build --release --target aarch64-unknown-linux-musl
      
      - name: Save the file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: NjtechQuickLogin-aarch64-unknown-linux-musl
          path: target/aarch64-unknown-linux-musl/release/NjtechQuickLogin

  publish:
    needs: 
      - build-x86_64-unknown-linux-musl
      - build-x86_64-unknown-linux-gnu
      - build-aarch64-unknown-linux-gnu
      - build-aarch64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./bin_files
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          name: "Release: ${{ github.ref_name }}"
          files: |
            ./bin_files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
