name: CI with Docker and Rust

on:
    workflow_dispatch:
      inputs:
        arch:
          description: '体系结构'
          required: true
          default: 'x86_64'
          type: choice
          options:
            - x86_64-unknown-linux-musl
            - x86_64-unknown-linux-gnu
            - x86_64-pc-windows-gnu
            - x86_64-linux-android
            - mips64-unknown-linux-gnuabi64
            - mips64el-unknown-linux-gnuabi64
            - aarch64-unknown-linux-gnu
            - aarch64-unknown-linux-musl
            - powerpc64le-unknown-linux-gnu
            - powerpc64-unknown-linux-gnu
            - aarch64-linux-android
            - loongarch64-unknown-linux-gnu
            - loongarch64-unknown-linux-musl

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the code
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Set up Rust environment
            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true

            # # Step 3: Install Docker
            # - name: Install Docker
            #   run: |
            #       sudo apt-get update
            #       sudo apt-get install -y docker.io
            #       sudo systemctl start docker
            #       sudo systemctl enable docker

            # Step 3: Verify installations
            - name: Check Rust and Docker
              run: |
                  rustc --version
                  cargo --version
                  docker --version

            # Step 4: Install cargo cross
            - name: Install cross-rs
              run: |
                  cargo install cross

            # Step 5: Build targets
            - name: Build ${{ github.event.inputs.arch }}
              run: |
                  cross build --release --target ${{ github.event.inputs.arch }}

            - name: Save the file as an artifact
              uses: actions/upload-artifact@v2
              with:
                name: NjtechQuickLogin-${{ github.event.inputs.arch }}
                path: target/${{ github.event.inputs.arch }}/release/NjtechQuickLogin